version: '3'

services:
  tests:
    build:
      context: .
    container_name: "playwright-tests"
    environment:
      - HTTP_CREDENTIALS_USERNAME=${HTTP_CREDENTIALS_USERNAME}
      - HTTP_CREDENTIALS_PASSWORD=${HTTP_CREDENTIALS_PASSWORD}
    network_mode: "host"
    volumes:
      - ./playwright-report:/playwright-tests/playwright-report